#include "thingProperties.h"  // Auto-generated by Arduino Cloud
#include <DHT.h>

#define DHTPIN A2     // Pin where the DHT11 is connected
#define DHTTYPE DHT11 

DHT dht(DHTPIN, DHTTYPE);

void setup() {
  Serial.begin(115200);
  delay(1000);

  dht.begin();
  
  // Connect to Arduino Cloud
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  // Wait for connection
  // while (ArduinoCloud.connected() == 0) {
  //   Serial.print(".");
  //   delay(500);
  // }
  Serial.println("Connected to Arduino Cloud");
}

void loop() {
  ArduinoCloud.update();  // Sync data with Arduino Cloud

  // Read DHT11 sensor data
  float temp = dht.readTemperature();
  float hum = dht.readHumidity();

  // Check if readings are valid
    temperature = temp;
    humidity = hum;

    Serial.print("Temperature: ");
    Serial.print(temperature);
    Serial.println(" °C");

    Serial.print("Humidity: ");
    Serial.print(humidity);
    Serial.println(" %");

    delay(5000); // Wait 5 seconds before next read
}